"""OpenMathInstruct-2 environment for Reliquary verifiable inference.

Loads Nvidia's OpenMathInstruct-2 dataset (14M math problems) generated by
Llama-3.1-405B from MATH + GSM8K. Pre-extracted ``expected_answer`` makes
reward computation more reliable than raw \\boxed{} parsing.

Disk-efficient strategy: only downloads the first N shards by default
(NVIDIA splits the dataset into 32 parquet shards of ~440k problems each;
2 shards = ~880k problems = >100x the per-window cooldown space).

Usage:
    env = OpenMathInstructEnvironment()
    p = env.get_problem(42)
    # {"prompt": "...", "ground_truth": "45", "id": "abc1234..."}
    reward = env.compute_reward(p, "the answer is \\boxed{45}")  # → 1.0
"""

from __future__ import annotations

import hashlib
import os
import re
from fractions import Fraction
from typing import ClassVar, Optional


# ---------------------------------------------------------------------------
# Answer extraction — reuse the balanced-brace parser from MATH env
# ---------------------------------------------------------------------------

def _last_boxed_only_string(text: str) -> Optional[str]:
    """Return the last \\boxed{...} / \\fbox{...} substring or None.

    Balanced-brace walk to handle nested expressions correctly.
    """
    idx = max(text.rfind("\\boxed{"), text.rfind("\\fbox{"))
    if idx < 0:
        return None
    try:
        open_idx = text.index("{", idx)
    except ValueError:
        return None
    depth = 0
    for j in range(open_idx, len(text)):
        c = text[j]
        if c == "{":
            depth += 1
        elif c == "}":
            depth -= 1
            if depth == 0:
                return text[idx : j + 1]
    return None


def _strip_boxed_wrapper(s: str) -> str:
    for prefix in (r"\boxed{", r"\fbox{"):
        if s.startswith(prefix) and s.endswith("}"):
            return s[len(prefix) : -1]
    return s


# ---------------------------------------------------------------------------
# Answer normalization — handles both LaTeX and plain numeric forms.
# OpenMathInstruct expected_answer is typically plain (e.g. "45", "3/4",
# "-2", "\\frac{1}{2}") so we accept both shapes.
# ---------------------------------------------------------------------------

_TEXT_RE = re.compile(r"\\text\{([^}]*)\}")
_MBOX_RE = re.compile(r"\\mbox\{([^}]*)\}")


def _normalize_answer(s: str) -> str:
    if s is None:
        return ""
    s = str(s)
    # Drop LaTeX spacing macros first
    for macro in (r"\!", r"\,", r"\ ", r"\;", r"\:"):
        s = s.replace(macro, "")
    s = s.replace(r"\left", "").replace(r"\right", "")
    s = s.replace(r"\dfrac", r"\frac").replace(r"\tfrac", r"\frac")
    # Strip unit decorations so a value with units matches the bare value
    # ("119^\circ" == "119"). These never carry numeric meaning for grading.
    s = re.sub(r"\^\s*\{?\s*\\circ\s*\}?", "", s)
    s = (s.replace(r"\circ", "").replace(r"\degree", "")
          .replace(r"\%", "").replace("%", ""))
    s = _TEXT_RE.sub(r"\1", s)
    s = _MBOX_RE.sub(r"\1", s)
    s = s.replace(r"\$", "").replace("$", "")
    # Plain-number normalization (OMI specific): "3.0" -> "3", "+5" -> "5"
    s = s.strip().rstrip(".").strip()
    s = re.sub(r"\s+", "", s)
    # Strip leading + on integers
    if len(s) > 1 and s[0] == "+":
        s = s[1:]
    # "3.0" -> "3" only when there's nothing else
    if re.fullmatch(r"-?\d+\.0+", s):
        s = s.split(".", 1)[0]
    return s


# ---------------------------------------------------------------------------
# Reward
# ---------------------------------------------------------------------------

_NUMERIC_RE = re.compile(r"[+-]?\d+(?:\.\d+)?(?:/\d+)?")


def _as_number(s: str) -> Optional[Fraction]:
    """Parse a plain integer / decimal / simple fraction as an exact Fraction.

    Returns None for anything else (LaTeX expressions, words, empty), so the
    caller can fall back to string comparison. Exact rationals avoid float
    rounding, so "82.50" == "82.5" and "1/2" == "0.5".
    """
    if not _NUMERIC_RE.fullmatch(s):
        return None
    try:
        return Fraction(s)
    except (ValueError, ZeroDivisionError):
        return None


def _latex_to_pyexpr(s: str) -> Optional[str]:
    """Rewrite the common LaTeX math macros (\\frac, \\sqrt, \\cdot, ...) into a
    plain Python/sympy expression. Returns None if any unknown ``\\macro``
    survives, so the caller falls back to string comparison rather than guess.
    """
    prev = None
    while prev != s:
        prev = s
        s = re.sub(r"\\sqrt\[([^\[\]{}]+)\]\{([^{}]+)\}", r"((\2)**(1.0/(\1)))", s)
        s = re.sub(r"\\sqrt\{([^{}]+)\}", r"sqrt((\1))", s)
        s = re.sub(r"\\(?:d|t)?frac\{([^{}]+)\}\{([^{}]+)\}", r"((\1)/(\2))", s)
    s = (s.replace(r"\cdot", "*").replace(r"\times", "*")
          .replace(r"\div", "/").replace(r"\pi", "pi"))
    s = s.replace("^", "**").replace("{", "(").replace("}", ")")
    return None if "\\" in s else s


def _expr_is_safe(expr, _depth: int = 0) -> bool:
    """Structural whitelist guarding ``evalf`` against adversarial payloads.

    Only numbers, named constants (pi, E), ``+ - * /`` and powers with a *small
    numeric* exponent (which also covers roots and ``1/x``) are allowed. Power
    towers (nested/symbolic exponents), huge exponents, factorials, other
    functions and free symbols are rejected — anything whose ``evalf`` could
    blow up on a miner-controlled boxed answer.
    """
    import sympy

    if _depth > 40:
        return False
    if expr.is_Number or isinstance(expr, sympy.NumberSymbol):
        return True
    if isinstance(expr, (sympy.Add, sympy.Mul)):
        return all(_expr_is_safe(a, _depth + 1) for a in expr.args)
    if isinstance(expr, sympy.Pow):
        base, exp = expr.as_base_exp()
        if not exp.is_Number:
            return False  # nested / symbolic exponent (e.g. a power tower)
        try:
            if abs(float(exp)) > 10:
                return False  # huge exponent
        except (TypeError, ValueError, OverflowError):
            return False
        return _expr_is_safe(base, _depth + 1)
    return False  # factorial, other functions, free symbols, ...


def _expr_str_is_safe(s: str) -> bool:
    """Token whitelist applied BEFORE ``parse_expr``.

    ``parse_expr`` eagerly evaluates some constructs during parsing (notably
    ``n!`` -> ``factorial(n)``), so a huge factorial would hang before the
    structural guard ever runs. Allow only digits, ``+ - * / ( ) .``, spaces and
    the tokens ``sqrt`` / ``pi``; anything else (``!``, function names like
    ``exp``/``gamma``/``factorial``, stray symbols) is rejected up front.
    """
    # Strip the allowed alpha tokens even when digit-adjacent ("2sqrt(5)") but
    # not when part of a longer identifier ("sqrtx"); whatever survives must be
    # numbers / operators only.
    cleaned = re.sub(r"(?<![A-Za-z])(?:sqrt|pi)(?![A-Za-z])", "", s)
    return re.fullmatch(r"[0-9.+\-*/() \t]*", cleaned) is not None


def _latex_value_equal(candidate: str, gt: str) -> bool:
    """Numeric value-equality for LaTeX answers, antlr-free and bounded.

    The candidate is a miner-controlled boxed payload, so two whitelists bound
    compute before any heavy evaluation: ``_expr_str_is_safe`` rejects tokens
    ``parse_expr`` would eager-evaluate (factorials, function names), and
    ``_expr_is_safe`` rejects power towers / huge exponents before ``evalf``.
    The length cap alone does not bound compute (``9^9^9^9`` is 7 chars but
    astronomically large). Returns False on any parse/eval error or disallowed
    structure.
    """
    if not candidate or not gt or len(candidate) > 100 or len(gt) > 100:
        return False
    ec, eg = _latex_to_pyexpr(candidate), _latex_to_pyexpr(gt)
    if ec is None or eg is None:
        return False
    if not (_expr_str_is_safe(ec) and _expr_str_is_safe(eg)):
        return False  # factorial / function name parse_expr would eager-evaluate
    try:
        from sympy.parsing.sympy_parser import (
            implicit_multiplication_application,
            parse_expr,
            standard_transformations,
        )
        tr = standard_transformations + (implicit_multiplication_application,)
        xc = parse_expr(ec, transformations=tr, evaluate=False)
        xg = parse_expr(eg, transformations=tr, evaluate=False)
        if not (_expr_is_safe(xc) and _expr_is_safe(xg)):
            return False
        vc = complex(xc.evalf())
        vg = complex(xg.evalf())
    except Exception:
        return False
    return abs(vc - vg) <= 1e-9 * (1 + abs(vg))


def _split_structure(s: str) -> Optional[list[str]]:
    """Split a matrix/vector/tuple into its ordered elements, else None.

    Lets a structured answer be compared element-by-element by value instead of
    by exact string, so per-entry surface form (fraction vs decimal) does not
    flip the reward. Scalars return None (handled by the scalar path).
    """
    m = re.search(r"\\begin\{[bp]?matrix\}(.*?)\\end\{[bp]?matrix\}", s, re.S)
    if m:
        return [c.strip() for row in m.group(1).split(r"\\") for c in row.split("&") if c.strip()]
    if len(s) >= 2 and s[0] in "([" and s[-1] in ")]" and "," in s:
        return [x.strip() for x in s[1:-1].split(",")]
    return None


def _answers_equal(candidate: str, gt: str) -> bool:
    """Compare by value when both sides are numbers, else by normalized string.

    The prompt asks for a value, so any surface form of that value is correct
    (trailing zeros, fraction vs decimal, \\frac{5721}{5} == 1144.2). Structured
    answers (matrix/vector/tuple) compare element-wise by value; scalars fall back
    to LaTeX value-equality, then exact normalized-string match.
    """
    cs, gs = _split_structure(candidate), _split_structure(gt)
    if cs is not None and gs is not None:
        return len(cs) == len(gs) and all(
            _answers_equal(_normalize_answer(a), _normalize_answer(b))
            for a, b in zip(cs, gs)
        )
    c, g = _as_number(candidate), _as_number(gt)
    if c is not None and g is not None:
        return c == g
    if candidate == gt:
        return True
    return _latex_value_equal(candidate, gt)


def _compute_omi_reward(problem: dict, completion: str) -> float:
    """Score an OMI completion.

    1.0 if the last \\boxed{...} matches expected_answer by value (numbers) or
    by normalized string (expressions). 0.0 otherwise. Never raises.
    """
    try:
        boxed = _last_boxed_only_string(completion)
        if boxed is None:
            # Fallback: try to find a trailing number / fraction at end of text
            # (some models output the answer without boxing)
            tail = completion.strip().split("\n")[-1].strip()
            # Match a leading number/fraction at start of last line
            m = re.match(r"^([\-\+]?\d+(?:\.\d+)?(?:/\d+)?)", tail)
            if m is None:
                return 0.0
            candidate = _normalize_answer(m.group(1))
        else:
            candidate = _normalize_answer(_strip_boxed_wrapper(boxed))
        gt = _normalize_answer(problem.get("ground_truth", ""))
        if gt == "":
            return 0.0
        return 1.0 if _answers_equal(candidate, gt) else 0.0
    except Exception:
        return 0.0


# ---------------------------------------------------------------------------
# Environment
# ---------------------------------------------------------------------------

# Appended to every OMI prompt so the answer format does not depend on the base
# model's default style. Without it, models that don't emit \boxed{} on their own
# (e.g. Qwen3.5) make reward extraction return 0. Shared by validator + miner via
# get_problem, so both encode the identical prompt (required for GRAIL consensus).
_ANSWER_FORMAT_INSTRUCTION = "\n\nPut your final answer within \\boxed{}."


class OpenMathInstructEnvironment:
    """Nvidia OpenMathInstruct-2: 14M synthetic math problems.

    Deterministic ``get_problem(idx)`` wraps modulo dataset length. The
    dataset is loaded once per process (HF caches under ~/.cache/huggingface).

    Disk strategy: ``RELIQUARY_OMI_SHARDS=N`` env var controls how many of
    the 32 parquet shards to download (default: 2 = ~880k problems, ~1GB).
    Each shard is ~440k problems / ~500MB. Increase if disk allows.
    """

    name: str = "openmathinstruct"

    _dataset_cache: ClassVar[Optional[object]] = None
    _DEFAULT_SHARDS: ClassVar[int] = 4

    def __init__(self) -> None:
        if OpenMathInstructEnvironment._dataset_cache is None:
            import datasets as hf
            n_shards = int(os.environ.get("RELIQUARY_OMI_SHARDS", str(self._DEFAULT_SHARDS)))
            n_shards = max(1, min(n_shards, 32))
            # Load only the first N shards by passing explicit data_files
            # verification_mode="no_checks" skips the metadata-mandated config
            # split set ({train_1M, train_2M, train_5M}) so we can pull
            # arbitrary parquet shards directly.
            data_files = [
                f"data/train-{i:05d}-of-00032.parquet" for i in range(n_shards)
            ]
            OpenMathInstructEnvironment._dataset_cache = hf.load_dataset(
                "nvidia/OpenMathInstruct-2",
                data_files=data_files,
                split="train",
                verification_mode="no_checks",
            )
        self._dataset = OpenMathInstructEnvironment._dataset_cache

    def __len__(self) -> int:
        return len(self._dataset)

    def get_problem(self, index: int) -> dict:
        """Deterministic lookup with modulo wrap.

        Note: dataset row order is fixed by parquet file order, so the same
        ``index`` always returns the same problem across miners that loaded
        the same shard set.
        """
        idx = index % len(self._dataset)
        row = self._dataset[idx]
        question: str = row["problem"]
        expected: str = str(row.get("expected_answer", ""))
        problem_id = hashlib.sha256(question.encode()).hexdigest()[:16]
        return {
            "prompt": question + _ANSWER_FORMAT_INSTRUCTION,
            "ground_truth": expected,
            "id": problem_id,
        }

    def compute_reward(self, problem: dict, completion: str) -> float:
        return _compute_omi_reward(problem, completion)
